// Route Paths — mirrors actual API routes at /api/v1/*
export const ENDPOINT = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    LOGOUT: "/auth/logout",
    PROFILE: "/auth/profile",
    REFRESH_TOKEN: "/auth/refresh-token",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
  },
  POSTS: {
    LIST: "/posts",
    MY_FEED: "/posts/feed/me",
    MY_WON_POSTS: "/posts/me",
    BY_USER: (userId) => `/posts/user/${userId}`,
    CREATE: "/posts",
    GET: (id) => `/posts/${id}`,
    UPDATE: (id) => `/posts/${id}`,
    DELETE: (id) => `/posts/${id}`,
  },
  COMMENTS: {
    LIST: (postId) => `/posts/${postId}/comments`,
    CREATE: (postId) => `/posts/${postId}/comments`,
    GET: (commentId) => `/comments/${commentId}`,
    UPDATE: (commentId) => `/comments/${commentId}`,
    DELETE: (commentId) => `/comments/${commentId}`,
    LIST_REPLIES: (commentId) => `/comments/${commentId}/replies`,
    ADD_REPLY: (commentId) => `/comments/${commentId}/replies`,
  },
  LIKES: {
    TOGGLE_POST: (postId) => `/likes/posts/${postId}/toggle`,
    TOGGLE_COMMENT: (commentId) => `/likes/comments/${commentId}/toggle`,
    LIST_POST: (postId) => `/likes/posts/${postId}`,
    LIST_COMMENT: (commentId) => `/likes/comments/${commentId}`,
    POST_STATS: (postId) => `/likes/posts/${postId}/stats`,
    COMMENT_STATS: (commentId) => `/likes/comments/${commentId}/stats`,
  },
  USERS: {
    ME: "/users/me",
    UPDATE_ME: "/users/me",
    SEARCH: "/users/search",
    GET: (id) => `/users/${id}`,
    TOGGLE_FOLLOW: (id) => `/users/${id}/follow`,
    FOLLOWERS: (id) => `/users/${id}/followers`,
    FOLLOWING: (id) => `/users/${id}/following`,
  },
  MESSAGES: {
    CONVERSATIONS: "/messages/conversations",
    GET_CONVERSATION: (userId) => `/messages/${userId}`,
    SEND: (userId) => `/messages/${userId}`,
    MARK_READ: (id) => `/messages/${id}/read`,
  },
  NOTIFICATIONS: {
    LIST: "/notifications",
    MARK_ALL_READ: "/notifications/read-all",
    MARK_READ: (id) => `/notifications/${id}/read`,
  },
  GROUPS: {
    LIST: "/groups",
    CREATE: "/groups",
    GET: (id) => `/groups/${id}`,
    UPDATE: (id) => `/groups/${id}`,
    DELETE: (id) => `/groups/${id}`,
    TOGGLE_MEMBERSHIP: (id) => `/groups/${id}/join`,
    MEMBERS: (id) => `/groups/${id}/members`,
    UPDATE_MEMBER_ROLE: (id, userId) => `/groups/${id}/members/${userId}`,
    FEED: (id) => `/groups/${id}/posts`,
    CREATE_POST: (id) => `/groups/${id}/posts`,
    DELETE_POST: (postId) => `/groups/posts/${postId}`,
    TOGGLE_POST_LIKE: (postId) => `/groups/posts/${postId}/like`,
    POST_COMMENTS: (postId) => `/groups/posts/${postId}/comments`,
    ADD_COMMENT: (postId) => `/groups/posts/${postId}/comments`,
    ADD_REPLY: (commentId) => `/groups/comments/${commentId}/replies`,
    DELETE_COMMENT: (commentId) => `/groups/comments/${commentId}`,
    TOGGLE_COMMENT_LIKE: (commentId) => `/groups/comments/${commentId}/like`,
  },
  STORIES: {
    LIST: "/stories",
    CREATE: "/stories",
    DELETE: (id) => `/stories/${id}`,
    REACT: (id) => `/stories/${id}/reaction`,
    REACTIONS: (id) => `/stories/${id}/reactions`,
  },
};
